account_manager/urls.py
from django.urls import path
from . import views

app_name = 'account_manager'

urlpatterns = [
    path('showaccounts', views.ShowAccountsView.as_view(), name="show_accounts"),
    path('createaccount', views.CreateAccountView.as_view(), name="create_account"),
    path('delete/<account_pk>', views.delete_account, name="delete_account")
]

cadastro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name="home_view"),
    path('account_manager/', include('account_manager.urls')),
]

account_manager/models.py
from django.db import models

# Create your models here.


class Account(models.Model):
    account_name = models.CharField(max_length=100)
    account_password = models.CharField(max_length=100)
    account_data = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.account_name

account_manager/forms.py
from django import forms


class CreateAccountForm(forms.Form):
    account_name = forms.CharField(max_length=100, label="Name")
    account_password = forms.CharField(
        max_length = 100, label="Password", widget=forms.PasswordInput())
    account_data = forms.CharField(max_length=200, label="Content")

account_manager/views.py
from django.shortcuts import redirect, render
from django import urls
from django import views
from . import models
from . import forms

# Create your views here.


class ShowAccountsView(views.View):

    def get(self, request):
        all_accounts = models.Account.objects.all()
        context = {
            "all_accounts": all_accounts,
        }
        return render(request, "account_manager/showaccounts.html", context=context)


class CreateAccountView(views.View):

    def get(self, request):
        form = forms.CreateAccountForm()
        return render(request, "account_manager/createaccount.html", context={"form": form})

    def post(self, request):
        all_accounts = models.Account.objects.all()
        form = forms.CreateAccountForm(request.POST)
        context = {
            "all_accounts": all_accounts,
            "form": form,
        }
        if form.is_valid():
            name = form["account_name"].value()
            password = form["account_password"].value()
            data = form["account_data"].value()
            models.Account.objects.create(
                account_name=name, account_password=password, account_data=data)
            context = {
                "all_accounts": all_accounts,
                "form": form,
            }
            return render(request, "account_manager/showaccounts.html", context=context)


def delete_account(request, account_pk):
    account = models.Account.objects.get(pk=account_pk)
    account.delete()
    return redirect(urls.reverse("account_manager:show_accounts"))

cadastro/views.py
from http.client import HTTPResponse
from django.shortcuts import render


def home_view(request):
    response: HTTPResponse = render(
        request=request, template_name="index.html")
    return response

account_manager/templates/account_manager/createaccount.html
{%extends "base.html"%}

{%block title%}
<title>Create Account</title>
{%endblock%}

{%block content%}
<form action="" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">Create Account</button>
</form>
{%endblock%}

account_manager/templates/account_manager/showaccounts.html
{%extends "base.html"%}

{%block title%}
<title>Accounts</title>
{%endblock%}

{%block content%}
<h1>Accounts</h1>
<h3><a href={%url 'home_view' %}>Home</a></h3>
<h3><a href={%url 'account_manager:create_account' %}>Create account</a></h3>
<ul>

    {% for account in all_accounts %}
    <li>Name: {{account.account_name}}<br>
        Description: {{account.account_data}}<br>
        <a href={% url "account_manager:delete_account" account_pk=account.pk %}>Delete</a>
    </li>
    {%endfor%}

</ul>

{%endblock%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block title%}
    <title>Document</title>
    {%endblock%}
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>

<body>
    {%block content%}
    {%endblock%}
</body>

</html>

templates/index.html
{%extends "base.html"%}

{%block title%}
<title>Home Page</title>
{%endblock%}

{%block content%}
<h1>Home page!</h1>

<h3><a href={%url 'account_manager:show_accounts' %}>Show accounts</a></h3>
<h3><a href={%url 'account_manager:create_account' %}>Create account</a></h3>
{%endblock%}